### ISSUE TITLE
Improve Prominence of Heading Outline Errors

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/mrw-web-design-simple-tinymce#74]
This plugin already increases the prominence of contrast errors in the sidebar. I wonder if there's a way I can highlight the extremely-buried flag for heading issues that is shown in the outline. Is there a :has() selector I can use? Is that error state somehow exposed in a place I can see it?

**Comment by oldrup** [comment]
@mrwweb, is it this you are looking for? 
![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/fcfa58c3-9303-4145-864c-9b136c61debc)

**Comment by mrwweb** [comment]
@oldrup That is indeed the error I'm thinking about. What I'd love is a way to flag that in a more prominent area so editors don't have to proactively look at the outline to discover the problem.

My initial idea would be to highlight the List View icon in the toolbar and add warning icon next to the Outline tab to lead editors to the problem. Here's a clunky mockup:

![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/1238696/97ccfb4f-9abc-4111-9484-160fef7d99a6)

**Comment by oldrup** [comment]
Hm.

Have you tried https://wordpress.org/plugins/accessibility-checker/ ?

It would notify you of poor heading structure, and more. Tests you don't want or need, can be disabled.

Will give some thoughts to this. :has might not be a bad idea.

Using simplified editor on four websites not. It's such a relief to be able to offer clients an editing experience where their risk of messing up the design (which they paid for) up. Constraints can be empowering.

**Comment by mrwweb** [comment]
@oldrup Yup, I know that plugin and also personally prefer the [Editoria11y checker](https://wordpress.org/plugins/editoria11y-accessibility-checker/).

The reason I'd want to add this is that the WP check is already there and this plugin seeks to not just hide less-useful features but play up other more useful ones like Save Draft, the contrast warning, and the Media Library. Highlighting the core heading warning feels in line with those goals.

So glad you're enjoying the plugin :)

**Comment by mrwweb** [comment]
Documenting something that _doesn't_ work:

```css
/*==============================================
=            Heading Outline Errors            =
==============================================*/
body:has(.document-outline__item.is-invalid) .editor-document-tools__document-overview-toggle {
	background-color: #f0b849 !important;
	color: #000 !important;
}
```

This works when the Outline tab is open, but the element with the `.is-invalid` class seems to not be in the page source when the outline view is closed. Therefore, it doesn't allow me to see that the headline has been marked invalid.

Getting a real solution then probably requires running the outline checker function (???) and adding a class to the body or something like that.
